services:
  npm:
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80" # HTTP
      - "81:81" # NPM 웹 UI
      - "443:443" # HTTPS
    volumes:
      - ./npm-data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped
